//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GALERİ
{
    using System;
    using System.Collections.Generic;
    
    public partial class araclar
    {
        public int aracno { get; set; }
        public Nullable<decimal> aracfiyat { get; set; }
        public Nullable<int> aracadet { get; set; }
        public string aracmarka { get; set; }
        public string aracmodel { get; set; }
        public string yıl { get; set; }
        public string ozellik { get; set; }
        public string motor { get; set; }
        public string paket { get; set; }
        public string renk { get; set; }
        public Nullable<int> subeno { get; set; }
    
        public virtual subeler subeler { get; set; }
    }
}
