//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GALERİ
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class galeriEntities : DbContext
    {
        public galeriEntities()
            : base("name=galeriEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<araclar> araclars { get; set; }
        public DbSet<musteriler> musterilers { get; set; }
        public DbSet<subeler> subelers { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<kullanıcılar> kullanıcılar { get; set; }
    }
}
