//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GALERİ
{
    using System;
    using System.Collections.Generic;
    
    public partial class musteriler
    {
        public musteriler()
        {
            this.subelers = new HashSet<subeler>();
        }
    
        public int musterino { get; set; }
        public string adsoyad { get; set; }
        public Nullable<int> yas { get; set; }
        public Nullable<decimal> musteribakiye { get; set; }
    
        public virtual ICollection<subeler> subelers { get; set; }
    }
}
