//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GALERİ
{
    using System;
    using System.Collections.Generic;
    
    public partial class subeler
    {
        public subeler()
        {
            this.araclars = new HashSet<araclar>();
        }
    
        public int subeno { get; set; }
        public string subeadi { get; set; }
        public Nullable<int> calisansayisi { get; set; }
        public Nullable<decimal> subeciro { get; set; }
        public Nullable<int> musterino { get; set; }
    
        public virtual ICollection<araclar> araclars { get; set; }
        public virtual musteriler musteriler { get; set; }
    }
}
